//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Help.Stats {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Help.Stats.ILoginHistoryWCFService")]
    public interface ILoginHistoryWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpEFService/GetByID", ReplyAction="http://tempuri.org/IHelpEFService/GetByIDResponse")]
        string GetByID(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpEFService/GetByID", ReplyAction="http://tempuri.org/IHelpEFService/GetByIDResponse")]
        System.Threading.Tasks.Task<string> GetByIDAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpEFService/GetAll", ReplyAction="http://tempuri.org/IHelpEFService/GetAllResponse")]
        string GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpEFService/GetAll", ReplyAction="http://tempuri.org/IHelpEFService/GetAllResponse")]
        System.Threading.Tasks.Task<string> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginHistoryWCFService/GetLoginInfoByUser", ReplyAction="http://tempuri.org/ILoginHistoryWCFService/GetLoginInfoByUserResponse")]
        string GetLoginInfoByUser(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginHistoryWCFService/GetLoginInfoByUser", ReplyAction="http://tempuri.org/ILoginHistoryWCFService/GetLoginInfoByUserResponse")]
        System.Threading.Tasks.Task<string> GetLoginInfoByUserAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginHistoryWCFServiceChannel : ILoginHistoryWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginHistoryWCFServiceClient : System.ServiceModel.ClientBase<ILoginHistoryWCFService>, ILoginHistoryWCFService {
        
        public LoginHistoryWCFServiceClient() {
        }
        
        public LoginHistoryWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginHistoryWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginHistoryWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginHistoryWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetByID(int value) {
            return base.Channel.GetByID(value);
        }
        
        public System.Threading.Tasks.Task<string> GetByIDAsync(int value) {
            return base.Channel.GetByIDAsync(value);
        }
        
        public string GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<string> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public string GetLoginInfoByUser(int ID) {
            return base.Channel.GetLoginInfoByUser(ID);
        }
        
        public System.Threading.Tasks.Task<string> GetLoginInfoByUserAsync(int ID) {
            return base.Channel.GetLoginInfoByUserAsync(ID);
        }
    }
}
